//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hack.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeType
    {
        public PracticeType()
        {
            this.Practices = new HashSet<Practice>();
            this.PracticeTypeThresholds = new HashSet<PracticeTypeThreshold>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Practice> Practices { get; set; }
        public virtual ICollection<PracticeTypeThreshold> PracticeTypeThresholds { get; set; }
    }
}
